### ISSUE TITLE
SSL Issue

### ISSUE THREAD

**Issue by randompants** [jalama/drupdates#87]
```/Library/Python/2.7/site-packages/requests-2.6.0-py2.7.egg/requests/packages/urllib3/util/ssl_.py:79: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning```

**Comment by jalama** [comment]
I'm not sure what caused these warning to suddenly start showing up, I suspect it's something to do with Stash in the environment we're testing in.  The fix applied to #85 looks to turn this only into a warning. Per https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning this looks like it's an issue only with older version of Python, can you run "python --version"?  To that end I'm gonna close this for now.
